#######################################################################
#                       Travis CI configuration                       #
#######################################################################
# Author: Joris Rietveld <jorisrieveld@gmail.com>                     #
# Created: 17-05-2017 18:20                                           #
# Project: WaterUp-Arduino-joris                                      #
#---------------------------------------------------------------------#
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # Configure the project'sensors entry point as an environment variable so the compiler knows where to start.
    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    # Install platformio with pip so we can test if the project compiles.
    - pip install -U platformio
    # Install an library for MQTT communication to our broker specifically written for the Adafruit Huzzah board.
    - platformio lib -g install "Adafruit MQTT Library"
    # Install an library for streaming C++ style output with operator <<
    - platformio lib -g install Streaming
    # Install an library for controlling the led's
    - platformio lib -g installAdafruit NeoPixel
    # Install an library configuring wifi connection parameters.
    - platformio lib -g install WifiManager
    # Install an library for parsing incoming mqtt messages containing configuration.
    - platformio lib -g install ArduinoJson
script:
     # Build the project with platformio for the Huzzah board.
    - platformio ci --project-conf=./platoformio.ini